### ISSUE TITLE
can not work with new swift version

### ISSUE THREAD

**Issue by tintin1926** [biezhihua/libdsm#13]
.pub-cache/hosted/pub.dartlang.org/libdsm-1.0.1/ios/Classes/SwiftDsmPlugin.swift:3:8: error: module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3.2 compiler: ios/.symlinks/plugins/libdsm/ios/libdsm_ios.framework/Modules/libdsm_ios.swiftmodule/arm64-apple-ios.swiftmodule.

I think the framework compiled with swift 5.1.3, and can not work with XCode 12.4. Could you make a new one or tell me how to make it?

**Comment by biezhihua** [comment]
I've upgraded to 14.4
